### ISSUE TITLE
Arcs rendered in attached gerber do not render properly.

### ISSUE THREAD

**Issue by gadgetjunkie** [mcous/gerber-to-svg#23]
The gerber in pcb.bor.txt renders correctly in gcpreview and gerbv.

It has issues when displaying the svn generated by gerber-to-svg.

The attached png file is a screenshot of the file being displayed in gerbv.

It looks like gerber-to-svg is having trouble with the tight arcs.
![screen shot 2015-11-17 at 10 21 45 pm](https://cloud.githubusercontent.com/assets/12651162/11277311/0c98eb22-8eb4-11e5-81c5-1fa85a64fddc.png)
[pcb.bor.txt](https://github.com/mcous/gerber-to-svg/files/39207/pcb.bor.txt)

**Comment by mcous** [comment]
This has been fixed in mcous/gerber-plotter@f674c05. It will be fixed here at `v1.0.0` when this library switches over to using the gerber-parser and gerber-plotter npm libraries.
