### ISSUE TITLE
Feature Request: Route mode in drill files does not render

### ISSUE THREAD

**Issue by gadgetjunkie** [mcous/gerber-to-svg#24]
Route mode (G00/G01) in drill files do not render as an actual slot/route, but instead appear as two individual drills at the start and end.  

Not a high priority, just something I noticed

**Comment by mcous** [comment]
Finally getting around to implementing this via mcous/gerber-parser#6. @gadgetjunkie have you ever seen any of the arc routing (G02/3) used in drill files? I'm wondering how far I should go with this.

**Comment by gadgetjunkie** [comment]
Hi Mike,

While I have only seen the linear routing (G01) in drill files so far, I would not be surprised to find one with arcs.   I have seen lots of odd shaped boards that would require arcs .

— Mike Williams
MacroFab, Inc.

**Comment by mcous** [comment]
Drill routing (linear and arc) is supported in v1.0.0
